
env:
  Creds: ${{ secrets.AZURE_MAG_CREDENTIALS }}
  SubscriptionID1: ${{ secrets.AZURE_MAG_SUB1 }}
  ResourceGroup1Name:  "Bicep-GH1"
  AzureCloudEnvironment:  "AzureUSGovernment"
  DeploymentName: "ActiveDirectory-Single-Site"
  TimeZone1:  "Eastern Standard Time"
  AutoShutdownEnabled:  "Yes"
  AutoShutdownTime: "2000"
  AutoShutdownEmail: "somename@domain.com"
  adminUsername:  ${{ secrets.adminUsername }}
  adminPassword:  ${{ secrets.adminPassword }}  
  WindowsServerLicenseType: 'Windows_Server'
  WindowsClientLicenseType: 'Windows_Client'
  NamingConvention: "khl"
  SubDNSDomain: ""
  SubDNSBaseDN: ""  
  NetBiosDomain:  "killerhomelab"
  InternalDomain: "killerhomelab"
  InternalTLD:  "com"  
  VNet1ID:  "10.1"
  ReverseLookup1: "1.10"      
  DC1OSVersion: "2022-Datacenter"
  WK1OSVersion: "Windows-11"
  DC1VMSize:  "Standard_D2s_v3"  
  WK1VMSize:  "Standard_D2s_v3"    
  Location1: "USGovVirginia"
  artifactsLocation: "https://raw.githubusercontent.com/elliottfieldsjr/KillerHomeLab-Bicep/main/Deployments"
  artifactsLocationSasToken: ""
  
on: [push]
name: '{{ DeploymentName }}'
jobs:
  "${{env.DeploymentName}}":
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: "${{env.Creds}}"
        environment: "${{env.AzureCloudEnvironment}}"

    - name: '{{ DeploymentName }}'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: "${{env.Subscription1ID}}"
        resourceGroupName: "${{env.ResourceGroup1Name}}"
        template: Deployments/ActiveDirectory-Single-Site/azuredeploy.bicep
        parameters:
          TimeZone1="${{env.TimeZone1}}"
          AutoShutdownEnabled="${{env.AutoShutdownEnabled}}"
          AutoShutdownTime="${{env.AutoShutdownTime}}"
          AutoShutdownEmail="${{env.AutoShutdownEmail}}"          
          adminUsername="${{env.adminUsername}}"
          adminPassword="${{env.adminPassword}}"
          WindowsServerLicenseType="${{env.WindowsServerLicenseType}}"
          WindowsClientLicenseType="${{env.WindowsClientLicenseType}}"          
          NamingConvention="${{env.NamingConvention}}"
          SubDNSDomain="${{env.SubDNSDomain}}"
          SubDNSBaseDN="${{env.SubDNSBaseDN}}"                    
          NetBiosDomain="${{env.NetBiosDomain}}"
          InternalDomain="${{env.InternalDomain}}"
          InternalTLD="${{env.InternalTLD}}"          
          VNet1ID="${{env.VNet1ID}}"
          DC1OSVersion="${{env.DC1OSVersion}}"
          WK1OSVersion="${{env.WK1OSVersion}}"          
          DC1VMSize="${{env.DC1VMSize}}"          
          WK1VMSize="${{env.WK1VMSize}}"                    
          ReverseLookup1="${{env.ReverseLookup1}}"          
          Location1="${{env.Location1}}"
          artifactsLocation="${{env.artifactsLocation}}/${{env.DeploymentName}}/"
          artifactsLocationSasToken="${{env.artifactsLocationSasToken}}"
