
env:
  Creds: ${{ secrets.AZURE_MAG2_CREDENTIALS }}
  SubscriptionID1: ${{ secrets.AZURE_MAG_SUB2 }}
  ResourceGroup1Name:  "Bicep-GH1"
  ResourceGroup2Name:  "Bicep-GH2"
  AzureCloudEnvironment:  "AzureUSGovernment"
  DeploymentName: "ActiveDirectory-Multi-Site"
  TimeZone1:  "Eastern Standard Time"
  TimeZone2:  "Eastern Standard Time"
  AutoShutdownEnabled:  "Yes"
  AutoShutdownTime: "2000"
  AutoShutdownEmail: "somename@domain.com"
  adminUsername:  ${{ secrets.adminUsername }}
  adminPassword:  ${{ secrets.adminPassword }}  
  WindowsServerLicenseType: 'Windows_Server'
  WindowsClientLicenseType: 'Windows_Client'
  NamingConvention: "khl"
  SubDNSDomain: ""
  SubDNSBaseDN: ""  
  NetBiosDomain:  "killerhomelab"
  InternalDomain: "killerhomelab"
  InternalTLD:  "com"  
  VNet1ID:  "10.1"
  VNet2ID:  "10.2"  
  ReverseLookup1: "1.10"      
  ReverseLookup2: "2.10"        
  DC1OSVersion: "2022-Datacenter"
  DC2OSVersion: "2022-Datacenter"  
  WK1OSVersion: "Windows-11"
  WK2OSVersion: "Windows-10"  
  DC1VMSize:  "Standard_D2s_v3"  
  DC2VMSize:  "Standard_D2s_v3"    
  WK1VMSize:  "Standard_D2s_v3"    
  WK2VMSize:  "Standard_D2s_v3"      
  Location1: "USGovVirginia"
  Location2: "USGovTexas"  
  artifactsLocation: "https://raw.githubusercontent.com/elliottfieldsjr/KillerHomeLab-Bicep/main/Deployments"
  artifactsLocationSasToken: ""  
  
on: [push]
name: Deployment
jobs:
  Deploy-Resources:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: "${{env.Creds}}"
        environment: "${{env.AzureCloudEnvironment}}"

    - name: Site1
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: "${{env.Subscription1ID}}"
        scope: subscription
        region: "${{env.Location1}}"
        template: "Deployments/${{env.DeploymentName}}/AzureDeploySite1.bicep"
        parameters:
          ResourceGroup1Name="${{env.ResourceGroup1Name}}"
          ResourceGroup2Name="${{env.ResourceGroup2Name}}"          
          TimeZone1="${{env.TimeZone1}}"
          AutoShutdownEnabled="${{env.AutoShutdownEnabled}}"
          AutoShutdownTime="${{env.AutoShutdownTime}}"
          AutoShutdownEmail="${{env.AutoShutdownEmail}}"          
          adminUsername="${{env.adminUsername}}"
          adminPassword="${{env.adminPassword}}"
          WindowsServerLicenseType="${{env.WindowsServerLicenseType}}"
          WindowsClientLicenseType="${{env.WindowsClientLicenseType}}"          
          NamingConvention="${{env.NamingConvention}}"
          SubDNSDomain="${{env.SubDNSDomain}}"
          SubDNSBaseDN="${{env.SubDNSBaseDN}}"                    
          NetBiosDomain="${{env.NetBiosDomain}}"
          InternalDomain="${{env.InternalDomain}}"
          InternalTLD="${{env.InternalTLD}}"          
          VNet1ID="${{env.VNet1ID}}"
          VNet2ID="${{env.VNet2ID}}"          
          DC1OSVersion="${{env.DC1OSVersion}}"
          WK1OSVersion="${{env.WK1OSVersion}}"          
          DC1VMSize="${{env.DC1VMSize}}"          
          WK1VMSize="${{env.WK1VMSize}}"                    
          ReverseLookup1="${{env.ReverseLookup1}}"          
          ReverseLookup2="${{env.ReverseLookup2}}"                    
          Location1="${{env.Location1}}"
          Location2="${{env.Location2}}"          
          artifactsLocation="${{env.artifactsLocation}}/${{env.DeploymentName}}/"
          artifactsLocationSasToken="${{env.artifactsLocationSasToken}}"                 

    - name: Site2
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: "${{env.Subscription1ID}}"
        scope: subscription
        region: "${{env.Location2}}"
        template: "Deployments/${{env.DeploymentName}}/AzureDeploySite2.bicep"
        parameters:
          ResourceGroup1Name="${{env.ResourceGroup1Name}}"
          ResourceGroup2Name="${{env.ResourceGroup2Name}}"
          TimeZone2="${{env.TimeZone2}}"          
          AutoShutdownEnabled="${{env.AutoShutdownEnabled}}"
          AutoShutdownTime="${{env.AutoShutdownTime}}"
          AutoShutdownEmail="${{env.AutoShutdownEmail}}"          
          adminUsername="${{env.adminUsername}}"
          adminPassword="${{env.adminPassword}}"
          WindowsServerLicenseType="${{env.WindowsServerLicenseType}}"
          WindowsClientLicenseType="${{env.WindowsClientLicenseType}}"          
          NamingConvention="${{env.NamingConvention}}"
          SubDNSDomain="${{env.SubDNSDomain}}"
          SubDNSBaseDN="${{env.SubDNSBaseDN}}"                    
          NetBiosDomain="${{env.NetBiosDomain}}"
          InternalDomain="${{env.InternalDomain}}"
          InternalTLD="${{env.InternalTLD}}"          
          VNet2ID="${{env.VNet2ID}}"          
          DC2OSVersion="${{env.DC2OSVersion}}"          
          WK2OSVersion="${{env.WK2OSVersion}}"                    
          DC2VMSize="${{env.DC2VMSize}}"                    
          WK2VMSize="${{env.WK2VMSize}}"                              
          Location1="${{env.Location2}}"  
          Location2="${{env.Location2}}"  
          artifactsLocation="${{env.artifactsLocation}}/${{env.DeploymentName}}/"
          artifactsLocationSasToken="${{env.artifactsLocationSasToken}}"                            