
env:
  TimeZone1:  "Eastern Standard Time"
  AutoShutdownEnabled:  "Yes"
  AutoShutdownTime: "2000"
  AutoShutdownEmail: "somename@domain.com"
  adminUsername:  ${{ secrets.adminUsername }}
  adminPassword:  ${{ secrets.adminPassword }}  
  WindowsServerLicenseType: 'Windows_Server'
  NamingConvention: "khl"
  VNet1ID:  "10.1"
  DC1OSVersion: "2022-Datacenter"
  DC1VMSize:  "Standard_D2s_v3"
  Location1: "USGovVirginia"
  SubDNSDomain: ""
  NetBiosDomain:  "killerhomelab"
  InternalDomain: "killerhomelab"
  InternalTLD:  "com"
  artifactsLocation: "https://raw.githubusercontent.com/elliottfieldsjr/KillerHomeLab-Bicep/main/Deployments/ActiveDirectory-Single-Site/"
  artifactsLocationSasToken: ""
  
on: [push]
name: ActiveDirectory-Single-Site
jobs:
  Deploy-ActiveDirectory-Site1:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_MAG_CREDENTIALS }}
        environment: 'AzureUSGovernment'

    - name: Deploy VNet1
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_MAG_SUB1 }}
        resourceGroupName: ${{ secrets.AZURE_RG1 }}
        template: Deployments/ActiveDirectory-Single-Site/azuredeploy.bicep
        parameters:
          TimeZone1="${{env.TimeZone1}}"
          adminUsername="${{env.adminUsername}}"
          adminPassword="${{env.adminPassword}}"
          WindowsServerLicenseType="${{env.WindowsServerLicenseType}}"
          NamingConvention="${{env.NamingConvention}}"
          VNet1ID="${{env.VNet1ID}}"
          DC1OSVersion="${{env.DC1OSVersion}}"
          DC1VMSize="${{env.DC1VMSize}}"          
          AutoShutdownEnabled="${{env.AutoShutdownEnabled}}"
          AutoShutdownTime="${{env.AutoShutdownTime}}"
          AutoShutdownEmail="${{env.AutoShutdownEmail}}"
          Location1="${{env.Location1}}"
          SubDNSDomain="${{env.SubDNSDomain}}"
          NetBiosDomain="${{env.NetBiosDomain}}"
          InternalDomain="${{env.InternalDomain}}"
          InternalTLD="${{env.InternalTLd}}"
          artifactsLocation="${{env.artifactsLocation}}"
          artifactsLocationSasToken="${{env.aartifactsLocationSasToken}}"
