
env:
  NamingConvention: "khl"
  Vnet1ID: "10.11"
  Location1:   "USGovVirginia"
  
on: [push]
name: ActiveDirectory-Single-Site
jobs:
  Deploy-Infrastructure:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_MAG_CREDENTIALS }}
        environment: 'AzureUSGovernment'

      # Deploy Virtual Network
    - name: Deploy VNet1
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_MAG_SUB1 }}
        resourceGroupName: ${{ secrets.AZURE_RG1 }}
        template: ../deployments/ActiveDirectory-Single-Site/linkedtemplates/vnet.bicep
        parameters:
          vnetName="${{env.NamingConvention}}-VNet1"
          vnetprefix="${{env.Vnet1ID}}.0.0/16"
          subnet1Name="${{env.NamingConvention}}-VNet1-Subnet1"
          subnet1Prefix="${{env.Vnet1ID}}.1.0/24"
          subnet2Name="${{env.NamingConvention}}-VNet1-Subnet2"
          subnet2Prefix="${{env.Vnet1ID}}.2.0/24"  
          BastionsubnetPrefix="${{env.Vnet1ID}}.253.0/24"  
          location="${{env.Location1}}"        
