
env:
  TimeZone1:  "Eastern Standard Time"
  adminUsername:  ${{ secrets.adminUsername }}
  adminPassword:  ${{ secrets.adminPassword }}  
  WindowsServerLicenseType: "Windows_Server"
  WindowsClientLicenseType: "Windows_Client"
  NamingConvention: "khl"
  SubDNSDomain: ""
  SubDNSBaseDN: ""
  NetBiosDomain:  "killerhomelab"
  InternalDomain: "killerhomelab"
  InternalTLD:  "com"
  ExternalDomain: "killerhomelab"
  ExternalTLD:  "com"  
  VNet1ID:  "10.1"
  ReverseLookup1: "1.10"
  DC1OSVersion: "2022-Datacenter"
  WK1OSVersion: "Windows-11"
  DC1VMSize:  "Standard_D2s_v3"
  WK1VMSize:  "Standard_D2s_v3"
  Location1:  "USGovVirginia"  
  
on: [push]
name: ActiveDirectory-Single-Site
jobs:
  Deploy-ActiveDirectory-Site1:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_MAG_CREDENTIALS }}
        environment: 'AzureUSGovernment'

    - name: Deploy VNet1
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_MAG_SUB1 }}
        resourceGroupName: ${{ secrets.AZURE_RG1 }}
        template: Deployments/ActiveDirectory-Single-Site/azuredeploy.bicep
        parameters:
          TimeZone="${{env.TimeZone1}}"
          adminUsername="${{env.adminUsername}}"
          adminPassword="${{env.adminPassword}}"
          WindowsServerLicenseType="${{env.WindowsServerLicenseType}}"
          WindowsClientLicenseType="${{env.WindowsClientLicenseType}}"
          NamingConvention="${{env.NamingConvention}}"
          SubDNSDomain="${{env.SubDNSDomain}}"
          SubDNSBaseDN="${{env.SubDNSBaseDN}}"
          NetBiosDomain="${{env.NetBiosDomain}}"
          InternalDomain="${{env.InternalDomain}}"
          InternalTLD="${{env.InternalDomain}}"
          ExternalDomain="${{env.ExternalDomain}}"
          ExternalTLD="${{env.ExternalTLD}}"
          VNet1ID="${{env.VNet1ID}}"
          ReverseLookup1="${{env.ReverseLookup1}}"
          DC1OSVersion="${{env.DC1OSVersion}}"
          WK1OSVersion="${{env.WK1OSVersion}}"
          DC1VMSize="${{env.DC1VMSize}}"
          WK1VMSize="${{env.WK1VMSize}}"
          Location1="${{env.Location1}}"                                                                                             
