
env:
  NamingConvention: "khl"
  VNet1ID:  "10.1"
  Location1:  "USGovVirginia"  
  
on: [push]
name: ActiveDirectory-Single-Site
jobs:
  Deploy-ActiveDirectory-Site1:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_MAG_CREDENTIALS }}
        environment: 'AzureUSGovernment'

    - name: Deploy VNet1
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_MAG_SUB1 }}
        resourceGroupName: ${{ secrets.AZURE_RG1 }}
        template: Deployments/ActiveDirectory-Single-Site/azuredeploy.bicep
        parameters:
          NamingConvention="${{env.NamingConvention}}"
          VNet1ID="${{env.VNet1ID}}"
          Location1="${{env.Location1}}"                                                                                             
