
env:
  Creds: ${{ secrets.AZURE_MAG2_CREDENTIALS }}
  SubscriptionID1: ${{ secrets.AZURE_MAG_SUB2 }}
  ResourceGroup1Name:  "Child-Domain-GH3"
  AzureCloudEnvironment:  "AzureUSGovernment"
  DeploymentName: "ActiveDirectory-Child-Domain"
  TimeZone1:  "Eastern Standard Time"
  TimeZone2:  "Pacific Standard Time"
  AutoShutdownEnabled:  "Yes"
  AutoShutdownTime: "2000"
  AutoShutdownEmail: "somename@domain.com"
  adminUsername:  ${{ secrets.adminUsername }}
  adminPassword:  ${{ secrets.adminPassword }}  
  WindowsServerLicenseType: 'Windows_Server'
  WindowsClientLicenseType: 'Windows_Client'
  NamingConvention: "khl"
  SubDNSDomain: ""
  SubDNSBaseDN: ""  
  ParentNetBiosDomain:  "killerhomelab"
  ParentDomain: "killerhomelab"
  ChildNetBiosDomain: "it"
  TLD:  "com"  
  VNet1ID:  "10.1"
  VNet2ID:  "10.2"  
  ReverseLookup1: "1.10"      
  ReverseLookup2: "2.10"        
  DC1OSVersion: "2022-Datacenter"
  DC2OSVersion: "2022-Datacenter"  
  WK1OSVersion: "Windows-11"
  WK2OSVersion: "Windows-11"  
  DC1VMSize:  "Standard_D2s_v3"  
  DC2VMSize:  "Standard_D2s_v3"    
  WK1VMSize:  "Standard_D2s_v3"    
  WK2VMSize:  "Standard_D2s_v3"      
  Location1: "USGovVirginia"
  Location2: "USGovArizona"  
  artifactsLocation: "https://raw.githubusercontent.com/elliottfieldsjr/KillerHomeLab-Bicep/main/Deployments"
  artifactsLocationSasToken: ""  
  
on: [push]
name: ActiveDirectory-Child-Domain
jobs:
  Deploy-Resources:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: "${{env.Creds}}"
        environment: "${{env.AzureCloudEnvironment}}"

    - name: Job1
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: "${{env.Subscription1ID}}"
        resourceGroupName: "${{env.ResourceGroup1Name}}"
        region: "${{env.Location1}}"
        template: "Deployments/${{env.DeploymentName}}/azuredeploy.bicep"
        parameters:
          Location1="${{env.Location1}}"
          Location2="${{env.Location2}}"          
          TimeZone1="${{env.TimeZone1}}"
          TimeZone2="${{env.TimeZone2}}"          
          AutoShutdownEnabled="${{env.AutoShutdownEnabled}}"
          AutoShutdownTime="${{env.AutoShutdownTime}}"
          AutoShutdownEmail="${{env.AutoShutdownEmail}}"          
          adminUsername="${{env.adminUsername}}"
          adminPassword="${{env.adminPassword}}"
          WindowsServerLicenseType="${{env.WindowsServerLicenseType}}"
          WindowsClientLicenseType="${{env.WindowsClientLicenseType}}"          
          NamingConvention="${{env.NamingConvention}}"
          SubDNSDomain="${{env.SubDNSDomain}}"
          SubDNSBaseDN="${{env.SubDNSBaseDN}}"                    
          ParentNetBiosDomain="${{env.ParentNetBiosDomain}}"
          ParentDomain="${{env.ParentDomain}}"
          ChildNetBiosDomain="${{env.ChildNetBiosDomain}}"          
          TLD="${{env.TLD}}"          
          VNet1ID="${{env.VNet1ID}}"
          VNet2ID="${{env.VNet2ID}}"  
          ReverseLookup1="${{env.ReverseLookup1}}"          
          ReverseLookup2="${{env.ReverseLookup2}}"                                      
          DC1OSVersion="${{env.DC1OSVersion}}"
          DC2OSVersion="${{env.DC2OSVersion}}"          
          WK1OSVersion="${{env.WK1OSVersion}}"          
          WK2OSVersion="${{env.WK2OSVersion}}"                    
          DC1VMSize="${{env.DC1VMSize}}"          
          DC2VMSize="${{env.DC2VMSize}}"                    
          WK1VMSize="${{env.WK1VMSize}}"                    
          WK2VMSize="${{env.WK2VMSize}}"                              
          artifactsLocation="${{env.artifactsLocation}}/${{env.DeploymentName}}/"
          artifactsLocationSasToken="${{env.artifactsLocationSasToken}}"                 